const { CustomError } = require('../middlewares/error');

// Ride handshake OTPs.
//
// These are NOT the Firebase/MSG91 auth OTPs — nothing is sent over SMS or
// email. They are generated by this service, stored on the booking row, and
// shown ONLY on the host's screen. The host reads the code aloud to the rider,
// who types it in. A correct code proves the two parties are physically
// together, which is the whole point of the handshake.
//
// Timing matters and is easy to get wrong:
//   - the START otp is issued when the booking is confirmed
//   - the END otp is issued when the ride actually starts, NOT at confirm time
// Issuing both up front (which is what the code used to do) means the end code
// exists, and is visible, for the entire booking — so a rider could be given
// both at handover and the end-of-ride check would prove nothing.

const generate = () => Math.floor(100000 + Math.random() * 900000);

const issueStartOtp = () => ({ startOtp: generate(), startOtpVerified: false });

const issueEndOtp = () => ({ endOtp: generate(), endOtpVerified: false });

// Both verifiers are deliberately strict about the "not issued yet" case:
// a null OTP must never compare equal to a null/absent submission, or the
// handshake could be skipped entirely by sending nothing.
const verifyStartOtp = (booking, submitted) => {
  if (booking.startOtp === null || booking.startOtp === undefined) {
    throw new CustomError('No start OTP has been issued for this booking', 400, 'OTP_NOT_ISSUED');
  }
  if (submitted === undefined || submitted === null || submitted === '') {
    throw new CustomError('Start OTP is required', 400, 'OTP_REQUIRED');
  }
  if (parseInt(submitted, 10) !== parseInt(booking.startOtp, 10)) {
    throw new CustomError('Invalid start OTP', 400, 'INVALID_OTP');
  }
};

const verifyEndOtp = (booking, submitted) => {
  if (booking.endOtp === null || booking.endOtp === undefined) {
    throw new CustomError('No end OTP has been issued — the ride must be started first', 400, 'OTP_NOT_ISSUED');
  }
  if (submitted === undefined || submitted === null || submitted === '') {
    throw new CustomError('End OTP is required', 400, 'OTP_REQUIRED');
  }
  if (parseInt(submitted, 10) !== parseInt(booking.endOtp, 10)) {
    throw new CustomError('Invalid end OTP', 400, 'INVALID_OTP');
  }
};

module.exports = { generate, issueStartOtp, issueEndOtp, verifyStartOtp, verifyEndOtp };
